name of input of yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,7 +3,7 @@ name: Auto Release
 on:
   workflow_dispatch:
     inputs:
-      Tag:
+      release:
         description: 'Type of release:'
         required: true
         default: 'patch'
@@ -22,7 +22,6 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
@@ -53,9 +52,7 @@ jobs:
           name: Logiciel Feuilles de caisses 
           path: ./dist/updater/  
 
-
-
-      - name: Generate new version based on commit message
+      - name: Generate new version based on input
         if: needs.commit_filter.outputs.should_run == 'true'
         run: |
           if ! latest_tag=$(git describe --tags --abbrev=0 2>/dev/null); then
@@ -66,22 +63,30 @@ jobs:
           major=$(echo "$latest_tag" | cut -d '.' -f 1 | sed 's/v//')
           minor=$(echo "$latest_tag" | cut -d '.' -f 2)
           patch=$(echo "$latest_tag" | cut -d '.' -f 3)
-          commit_message=$(git log -1 --pretty=%B)
           
-          if echo "$commit_message" | grep -iq "nouvelle version majeure"; then
-            major=$((major + 1))
-            minor=0
-            patch=0
-          elif echo "$commit_message" | grep -iq "nouvelle version mineure"; then
-            minor=$((minor + 1))
-            patch=0
-          elif echo "$commit_message" | grep -iq "nouveau patch"; then
-            patch=$((patch + 1))
-          fi
+          case "${{ github.event.inputs.release }}" in
+            major)
+              major=$((major + 1))
+              minor=0
+              patch=0
+              ;;
+            minor)
+              minor=$((minor + 1))
+              patch=0
+              ;;
+            patch)
+              patch=$((patch + 1))
+              ;;
+            *)
+              echo "Invalid input. No version change."
+              exit 1
+              ;;
+          esac
+          
           new_tag="v${major}.${minor}.${patch}"
           echo "New tag: $new_tag"
           echo "NEW_TAG=$new_tag" >> $GITHUB_ENV
-        shell: bash    
+        shell: bash
 
       - name: save new tag
         run: echo ${{ env.NEW_TAG }} > current_version.txt   
@@ -105,8 +110,8 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ./dist/main  # Retirez l'extension .exe pour Linux/macOS
-          asset_name: main.exe  # Vous pouvez toujours le nommer main.exe pour la clarté
+          asset_path: ./dist/main
+          asset_name: main.exe
           asset_content_type: application/octet-stream
 
       - name: Upload Updater Release Asset
@@ -115,6 +120,6 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ./dist/updater  # Retirez l'extension .exe pour Linux/macOS
-          asset_name: updater.exe  # Idem, l'extension .exe peut être ajoutée pour la clarté
+          asset_path: ./dist/updater 
+          asset_name: updater.exe 
           asset_content_type: application/octet-stream
